version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_service
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  centrifugo:
    image: centrifugo/centrifugo:v5.4.5
    command: centrifugo -c /centrifugo/config.json --admin --admin_insecure
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    ports:
      - "8001:8000"

  auth_service:
    build: ./backend
    ports:
      - "9080:9080"
    depends_on:
      - db

volumes:
  db_data:
